let mods=[],category='All';const list=document.querySelector('#mod-list'),search=document.querySelector('#mod-search');
function safe(text){return String(text??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function render(){const q=search.value.trim().toLowerCase();let shown=0;list.innerHTML=mods.map((m,i)=>{if((category!=='All'&&m.category!==category)||q&&!`${m.name} ${m.author} ${(m.creators??[]).join(' ')} ${m.description} ${m.note??''}`.toLowerCase().includes(q))return '';shown++;return `<details class="mod" id="mod-${safe(m.id)}"><summary><span class="mod-num">${String(i+1).padStart(2,'0')}</span><span class="mod-title">${safe(m.name)}</span><span class="mod-author">${safe(m.author)}</span><span class="mod-category">${safe(m.category)}</span><span class="mod-toggle" aria-hidden="true">+</span></summary><div class="mod-details"><p>${safe(m.description)}</p>${m.note?`<p class="mod-note">${safe(m.note)}</p>`:''}<div class="mod-links">${(m.links??[]).map(l=>`<a href="${safe(l.url)}" target="_blank" rel="noopener noreferrer">${safe(l.label)}</a>`).join('')}</div></div></details>`}).join('');document.querySelector('#result-count').textContent=`${shown} of ${mods.length} entries`;document.querySelector('#no-results').hidden=shown!==0;document.querySelectorAll('#filters button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.category===category)));}
function setCategory(c){category=c;render();}
function openHash(){const id=location.hash.slice(1);if(id.startsWith('mod-')){category='All';search.value='';render();const el=document.getElementById(id);if(el){el.open=true;setTimeout(()=>el.scrollIntoView({block:'start'}),50)}}}
fetch('mods.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{mods=data;const cats=['All',...new Set(mods.map(m=>m.category))];document.querySelector('#filters').innerHTML=cats.map(c=>`<button type="button" data-category="${safe(c)}" aria-pressed="${c==='All'}">${safe(c)}</button>`).join('');document.querySelector('#filters').addEventListener('click',e=>{const b=e.target.closest('button');if(b)setCategory(b.dataset.category)});search.addEventListener('input',render);document.querySelectorAll('[data-category-link]').forEach(a=>a.addEventListener('click',()=>{search.value='';setCategory(a.dataset.categoryLink)}));const creators=new Map();mods.forEach(m=>(m.creators??[m.author]).forEach(c=>{if(!/confirm|unverified|not identified|various/i.test(c))creators.set(c,(creators.get(c)||0)+1)}));document.querySelector('#creator-index').innerHTML=[...creators].sort((a,b)=>a[0].localeCompare(b[0])).map(([c,n])=>`<a class="creator" href="#mods" data-creator="${safe(c)}">${safe(c)}<small>${n}</small></a>`).join('');document.querySelector('#creator-index').addEventListener('click',e=>{const a=e.target.closest('[data-creator]');if(a){category='All';search.value=a.dataset.creator;render()}});render();openHash();}).catch(()=>{document.querySelector('#result-count').textContent='The directory could not load.';document.querySelector('#result-count').textContent='Search unavailable. The complete directory is shown below.'});window.addEventListener('hashchange',openHash);

document.querySelectorAll('[data-copy-target]').forEach(button=>button.addEventListener('click',async()=>{
  const field=document.getElementById(button.dataset.copyTarget),status=document.getElementById('copy-status');
  try{
    await navigator.clipboard.writeText(field.value);
    button.textContent='Copied';status.textContent='SHA-256 copied.';
    setTimeout(()=>{button.textContent='Copy hash';status.textContent=''},2500);
  }catch{
    field.focus();field.select();field.setSelectionRange(0,field.value.length);
    status.textContent='Hash selected. Copy it with Ctrl+C or Command+C.';
  }
}));
